module.exports = {
  mode: "jit",
  purge: ["./src/**/*.{vue,js}"],
  theme: {
    extend: {},
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#FFF",
      black: "#000",
      "primary-gray": "#292D32",
      "secondary-gray": "#666666",
      "primary-pink": "#F30168",
      "primary-green": "#10C300",
      "blue-gray": "#515D74",
      "blue-gray-80": "#515D7480",
      "ice-blue": "#E6EAF2",
      "red-error": "#FF0000",
      "light-gray": "#C4C4C480",
      silver: "#D9D9D9",
      "dark-purple": "#331d59",
      "off-white": "#fafafa",
    },
  },
  variants: {},
  plugins: [],
};
